# SPDX-License-Identifier: GPL-3.0-or-later
hostonly="no"
hostonly_cmdline="no"
early_microcode="yes"
compress="xz"
add_dracutmodules+=" systemd systemd-initrd devario-live dmsquash-live overlayfs livenet network-manager nfs nbd "
filesystems+=" squashfs overlay iso9660 vfat ext4 btrfs xfs f2fs "
omit_dracutmodules+=" systemd-sysusers-service "
